# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site # 站点基本信息
title: Fly with You # 网站标题
subtitle: 多谷黑芝麻 & 蜂蜜柚子茶
description: 记录生活 知识管理 思考感悟
author: Kubert
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: kuberme.cn
root: /
permalink: :title/
permalink_defaults:
# tag_dir: tags
# archive_dir: archives
# category_dir: categories
# code_dir: 

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100
multi_thread: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus # 社会化评论disqus
disqus_shortname: kuberme
#uoshuo_shortname: 

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
# theme: cnfeat
# theme: themia
theme: next
#theme: kuber-tranquilpeak
#exclude_generator:
#Plugins:

# Admin
admin: 
  name: hexo
  password: hey
  secret: hey hexo
  expire: 60*1
  # cors: http://localhost:3000

feed:
  type: atom
  path: atom.xml
  limit: 20

keywords:
  - hexo
  - javascript

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/kubertalk/kubertalk.github.io.git
  branch: master

# hexo sitemap网站地图
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

post_copyright:
  enable: true 
  author: kuber
  copyright_text: 作者拥有版权，请注明出处转载。
